### ISSUE TITLE
Missing the configuration file angular.json in ngrx-example-app

### ISSUE THREAD

**Issue by christophechevalier** [co-IT/ngrx-vis#26]
Hi !
I noticed that in the ngrx-example-app folder, you are missing the configuration file `angular.json`.
Therefore, it is impossible to use commands such as `ng serve`.

**Comment by GregOnNet** [comment]
Hi,

thanks for your message.
Currently, it is not intended to run the ngrx-example-app.

I copied the source from `@ngrx/platform`: https://github.com/ngrx/platform/tree/master/projects/example-app

The project is used to run static code analysis to check if ngrx-vis works...

You could clone `@ngrx/platform` to run the example app on you machine.

I close this issue for now.
Feel free to re-open it if I have missed something.
