### ISSUE TITLE
Overlapping labels

### ISSUE THREAD

**Issue by MrCube42** [co-IT/ngrx-vis#8]
Action and file names could be rather long. The graph drawing algorithm directly places the action and origin-file on the same row lane by lane. However the labels may overlap and become unreadable. The workaround is to manually pull one of the nodes slightly up or down. This may be something the tool could to while generating the graph.

Current:
![image](https://user-images.githubusercontent.com/8179639/78220713-52cf0d80-74c2-11ea-865d-69a292408267.png)

Suggestion:
![image](https://user-images.githubusercontent.com/8179639/78220761-67aba100-74c2-11ea-9939-59411b9426d1.png)

**Comment by GregOnNet** [comment]
Thank you for pointing this out.

There are a few things that can be done.
Version 0.1.15 renders the graph a bit differently and accidentally there are fewer overlabs.

Furthermore, a linebreak will be added after the action scope.

It would be nice if the action could be displayed differently.
Note as node but as heading.
Currently, I do not know how to achieve that with vis.js
